### ISSUE TITLE
Feature: cleanup old functions

### ISSUE THREAD

**Issue by erezrokah** [nimbella/netlify-plugin-nimbella#37]
Not sure if this is a feature. bug or a discussion.

Should the plugin remove old functions on each deploy? I noticed that if I delete a function locally and push the changes the endpoint is still available.

That might be confusing to some users.

**Comment by rabbah** [comment]
This is possible for a deploy that uses a nimbella project. Removing individual functions is otherwise tricky - the user could add functions out of band. 

We could add a feature to clean the namespace before a deploy which allows the user some control.  For example a build input which causes `nim namespace clean` to run.

**Comment by rabbah** [comment]
For a nimbella project, cleaning the namespace before deploying is controlled through the `project.yml`. See https://docs.nimbella.com/configuration#adding-project-configuration for discussion. The cleaning can occur at the level of a namespace, or package. I amended the docs in 782f796189fd42d0aa4489e49f89360f2b1112fe to mention this. Another feature we can consider is adding a `clean` flag to the plugin inputs to force cleaning the namespace irrespective of the project.yml setting. Deferring this until we have more feedback.
